/**
 * Python highlighting for code that is not in an editor.
 *
 * The notebook's cells are CodeMirror, and CodeMirror paints them. Everything
 * else that shows code was grey: an oracle answer, a proposed rewrite, the code
 * a turn offers to put in a new cell. That is most of the code a student reads
 * during a seminar — they read their own cells while writing them and read
 * everything else while being taught — and it was the half without colour.
 *
 * Nothing new is invented here. The parser is the one the editor uses and the
 * rules are the editor's own HighlightStyle, so a `def` in an answer is exactly
 * the `def` in the cell below it. What this module adds is the two steps
 * CodeMirror normally does inside a view: run the tree through the style, and
 * put that style's generated classes into the document.
 *
 * Loaded lazily, like the markdown renderers and for the same reason: the
 * grammar is weight the join screen has no use for. Until it lands, callers
 * render the code as plain text — which is code, just in one colour.
 */
import type { HighlightStyle } from '@codemirror/language'
import { spread, type Range, type Syntax } from './syntax'

export { diffTokens, plain, type Syntax, type Token } from './syntax'

async function importSyntax(): Promise<Syntax> {
  const [{ python }, { highlightTree }, { highlight }, { StyleModule }] = await Promise.all([
    import('@codemirror/lang-python').then(({ python }) => ({ python })),
    import('@lezer/highlight').then(({ highlightTree }) => ({ highlightTree })),
    import('@/components/notebook/cm-theme').then(({ highlight }) => ({ highlight })),
    import('style-mod').then(({ StyleModule }) => ({ StyleModule })),
  ])

  /*
   * The classes highlightTree hands back are generated by style-mod and mean
   * nothing until their rules are in the document. An editor mounts them as a
   * side effect of syntaxHighlighting(); nothing here does, so we mount them.
   * StyleModule keeps a set per root, so this is idempotent whether or not a
   * cell got there first.
   */
  const style = highlight as HighlightStyle
  if (style.module) StyleModule.mount(document, style.module)

  const parser = python().language.parser

  return {
    lines(code) {
      const ranges: Range[] = []
      highlightTree(parser.parse(code), style, (from, to, cls) => ranges.push({ from, to, cls }))
      return spread(code, ranges)
    },
  }
}

let loaded = $state<Syntax | null>(null)
let inFlight: Promise<Syntax> | null = null

/**
 * Idempotent: a thread of forty code blocks fetches the grammar once.
 *
 * A failure is not cached: a promise rejected by one dropped request would
 * leave the tab without highlighting until a reload — the next code block
 * tries again. The same caveat as for `loadRenderers`.
 */
export function loadSyntax(): Promise<Syntax> {
  return (inFlight ??= importSyntax()
    .then((ready) => {
      loaded = ready
      return ready
    })
    .catch((err: unknown) => {
      inFlight = null
      throw err
    }))
}

/**
 * The highlighter if it is here, null while the chunk is in flight. Reading it
 * inside a $derived is what repaints the code once it lands.
 */
export function syntax(): Syntax | null {
  return loaded
}
